### ISSUE TITLE
Combining agcontext and metadata editors on the same page.

### ISSUE THREAD

**Issue by geezacoleman** [Weed-AI/Weed-AI#429]
Reducing the number of links/clicks in the upload process would be ideal and combining the editors into one page with sections might be a low hanging fruit. Is it easy to do?

This is just a slightly edited example I saw on TCIA for their citing guidelines/FAQ

![Editor](https://user-images.githubusercontent.com/51358498/114329020-af5b1300-9b81-11eb-96f2-6b1d624aeb5e.png)

**Comment by jnothman** [comment]
Is this because you want to be able to edit metadata first?


From: Guy Coleman ***@***.***>
Reply to: Sydney-Informatics-Hub/Weed-AI ***@***.***>
Date: Monday, 12 April 2021 at 11:25 am
To: Sydney-Informatics-Hub/Weed-AI ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Sydney-Informatics-Hub/Weed-AI] Combining agcontext and metadata editors on the same page. (#429)


Reducing the number of links/clicks in the upload process would be ideal and combining the editors into one page with sections might be a low hanging fruit. Is it easy to do?

This is just a slightly edited example I saw on TCIA for their citing guidelines/FAQ

[Editor]<https://user-images.githubusercontent.com/51358498/114329020-af5b1300-9b81-11eb-96f2-6b1d624aeb5e.png>

**Comment by geezacoleman** [comment]
Mainly just so it flows better and I don't have to click through multiple pages to set it up

**Comment by jnothman** [comment]
Are you usually uploading prefab files rather than using the editor?

**Comment by geezacoleman** [comment]
I've used the editor for each upload - it makes it easy to edit. Sometimes I'll drag a drop a previous json into the editor to preset some fields, but then still use it to finish it off.

**Comment by jnothman** [comment]
I don't think this is going to happen  any time soon, sorry @geezacoleman. We have, however, reduced the clicks!

**Comment by geezacoleman** [comment]
I think the process is a lot easier now than it was back then, so no worries!
